export interface ApartmentListing {
    id: number; // id can be optional because it will be generated by the backend
    listingName: string;
    address: string;
    age: number;
    roomNumber: number;
    price: number;
    rentSale: 'RENT' | 'SALE';
    hasFurniture: boolean;
    hasBalcony: boolean;
    bathroomNumber: number;
    homeSquareMeter: number;
}